POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "kyron3",
    "password": "123abc"
}

##########

GET http://localhost:5000/api/users/usertest
Content-Type: application/json


###############

PUT http://localhost:5000/api/users/find/633a6fc39f94ad863df10219
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzM2E2ZmMzOWY5NGFkODYzZGYxMDIxOSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NjQ5MDYzODEsImV4cCI6MTY2NTE2NTU4MX0.xoCjJY0Re2J5qOzXtT3sir1Uij795EkiH6e81ZozWfo

{
    "username": "kyron3Update"
}


####
DELETE http://localhost:5000/api/users/633a6fc39f94ad863df10219
Content-Type: application/json

{
    "name": "M Fikri",
    "email": "email@gmail.com",
    "gendr": "male"
}